### ISSUE TITLE
Functions to implement for the package `listwiz`

### ISSUE THREAD

**Issue by Nikoleta-v3** [Nikoleta-v3/a-hitchhikers-guide-to-contributing-to-open-source#1]
### Sorting Algorithms

- ~Bubble Sort: https://en.wikipedia.org/wiki/Bubble_sort~
- Insertion Sort: https://en.wikipedia.org/wiki/Insertion_sort
- ~Selection Sort:~
- ~Merge Sort for us.~ 

### Lists manipulation/analysis 

- the longest increasing stick 
- the longest decreasing 
- the location and value of the smallest value
- the location and value of the largest value
- the element that occurs the most often

**Comment by seberg** [comment]
I have created an individual issue for all of these now, I think, so closing.
