### ISSUE TITLE
BUG: `replace_sublist` hangs with length 0 list inputs 

### ISSUE THREAD

**Issue by seberg** [Nikoleta-v3/a-hitchhikers-guide-to-contributing-to-open-source#11]
When using `replace_sublist` with a length 0 `sublist` the function never returns.

Instead of failing, the right thing seems to be to raise an informative `ValueError`.

### Minimal reproducer

```python
from listwiz.replace import replace_sublist

replace_sublist([1, 2, 3], [], [5, 6])
```

### Context

When working with `replace_sublist`, I accidentally passed an empty input as first list, causing the program to never finish.

### Working on the issue

To fix this issue:
1. Reproduce the issue locally
2. Find the `replace_sublist()` code
3. Modify the code (in either order):
   - Write a test which fails currently `main`, but should pass.  Please expand the existing `test_mergesort_empty` for this.
     To test whether an error is raised, you can use:
     ```
     with pytest.raises(ValueError, match="error message"):
         # code that raises the error.
     ````
   - Modify the code to check for a length 0 `sublist` and explicitly `raise ValueError("informative message")`.

Once you have done the changes, commit them to a new branch and create a PR!

**Comment by Anaaa** [comment]
I'll do it
