### ISSUE TITLE
ENH: Add `replace_elements` function

### ISSUE THREAD

**Issue by seberg** [Nikoleta-v3/a-hitchhikers-guide-to-contributing-to-open-source#12]
It would sometimes be nice to have a small helper function to replace elements of a list given a dictionary of replacements.  For example:
```
replace_elements([1, 2, 3], {2: 20, 3: 30})
```
would replace all `2`s with `20` and all  `3` with `30`.  So the result would be:
```
[1, 20, 30]
```

### Working on the issue

Implementing `replace_elements consists of the following things:
- Find the existing `replace_elements` stub and replace it with your implementation.
- Add documentation (you can look at `replace_sublist` for inspiration).
- Add some tests by expanding `test_replace_elements` in `test_replace.py`.

Once you have made your changes, and committed them to a new branch, you can create a PR and wait for feedback!

**Comment by andrea-petrocchi** [comment]
I'm on it.
