### ISSUE TITLE
ENH: Implement bubble sort

### ISSUE THREAD

**Issue by seberg** [Nikoleta-v3/a-hitchhikers-guide-to-contributing-to-open-source#9]
We currently have a small implementation of a merge sort algorithm only.  We would like to also provide a `bubble_sort` implementation.

For information on bubble sort, please see: https://en.wikipedia.org/wiki/Bubble_sort

### Working on this issue

Implementing bubblesort consists of the following things:
- Find the existing `bubble_sort` stub and replace it with your implementation.
- Add documentation (you can look at `merge_sort` for inspiration).
- Add some tests by expanding `test_bubble_sort` in `test_sorting.py`.

Once you have made your changes, and committed them to a new branch, you can create a PR!

**Comment by andrea-petrocchi** [comment]
I'm on it.

**Comment by Nikoleta-v3** [comment]
I am closing this. It was addressed by #30 and #31
